name: type checking

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy django-stubs
          pip install -e .
          pip install types-requests types-PyYAML types-toml
    
      - name: Run mypy
        run: |
          mypy vulnerabilities