name: type checking

on: [push, pull_request]

jobs:
  mypy:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.11

      - name: Install type checking dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy==1.3.0 django-stubs==4.2.0 types-requests==2.30.0.0 types-PyYAML==6.0.12.10 types-toml==0.10.8.6
          pip install Django djangorestframework packageurl-python univers license-expression

      - name: Run mypy
        run: |
          mypy vulnerabilities