# Generated by Django 4.2.17 on 2025-02-28 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0088_fix_alpine_purl_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisory",
            name="date_imported",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="UTC Date on which the advisory was imported",
            ),
        ),
    ]
